apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: scraper
spec:
  selector:
    matchLabels:
      app: scraper
  replicas: 1
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: eu.gcr.io/xomnia-search-engine-training/scraper
        imagePullPolicy: Always