apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: scraper
spec:
  selector:
    matchLabels:
      app: scraper
  replicas: 5
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: scraper-image
        imagePullPolicy: Never